### ISSUE TITLE
Portainer 2.9.0 update

### ISSUE THREAD

**Issue by tordenflesk** [GilbN/theme.park#259]
**Describe the bug**
Login-box, search-box ect. aren't themed after 2.9.0. update.

**Theme Install Method** (Don't skip)
- Stylus (@import "https://gilbn.github.io/theme.park/CSS/themes/portainer/space-gray.css";)

**Application Info** (Don't skip)
- 2.9.0
- portainer/portainer-ce:latest

**Screenshots**
https://i.imgur.com/2z38jyZ.png
https://i.imgur.com/HnVO5Yx.png

**Comment by GilbN** [comment]
Will fix when http://demo.portainer.io is updated as I dont use it.

**Comment by neo-neo1** [comment]
I just spent the last 2 hours trying to troubleshoot why theme.park isn't working for my Portainer install. Glad to see it was reported and will be fixed (I hope!). Thanks for maintaining this project

**Comment by neo-neo1** [comment]
Question for you @tordenflesk do you use Portainer in a docker? If so which maintainer?

**Comment by tordenflesk** [comment]
Docker image: portainer/portainer-ce:latest
Stylus for this particular theme.

**Comment by neo-neo1** [comment]
> Docker image: portainer/portainer-ce:latest Stylus for this particular theme.

Same here.
Have you (or anyone?) tried installing themes using the [DOCKER_MODS environmental variable ](https://docs.theme-park.dev/setup/#docker-mods)for Portainer? I can NOT get this method to work, and I successfully used it for Radarr/Prowlarr/etc.. and other Dockers. My Portainer version is 2.9.0 and I have not tried using an older portainer version with themes.

**Comment by GilbN** [comment]
> > Docker image: portainer/portainer-ce:latest Stylus for this particular theme.
> 
> I also use portainer/portainer-ce but... Have you (or anyone?) tried installing themes using the [DOCKER_MODS environmental variable ](https://docs.theme-park.dev/setup/#docker-mods)for Portainer? I can NOT get this method to work with Portainer, and I successfully used it for Radarr/Prowlarr/etc.. and other Docker Containers. My Portainer version is 2.9.0 (latest). What gives?

There's a note here https://docs.theme-park.dev/setup/#docker-mods 
Docker mods/init scripts is a lsio/hotio thing

**Comment by Dulanic** [comment]
Submitted PR to correct, very easy fix, just needed a !important flag.

**Comment by Dulanic** [comment]
It also looks like they may be working on dark mode directly which is what cause the issue. I am still digging in to see how to enable their default support now? 

https://github.com/portainer/portainer/pull/5353

**Comment by Dulanic** [comment]
> > It also looks like they may be working on dark mode directly which is what cause the issue. I am still digging in to see how to enable their default support now?
> > [portainer/portainer#5353](https://github.com/portainer/portainer/pull/5353)
> 
> Interesting, thanks for your work

It looks like this is related to their theme/helm work. I'll pass, it looks like a lot more work to implement :)

https://docs.portainer.io/v/ce-2.9/advanced/app-templates/format

**Comment by neo-neo1** [comment]
> > > It also looks like they may be working on dark mode directly which is what cause the issue. I am still digging in to see how to enable their default support now?
> > > [portainer/portainer#5353](https://github.com/portainer/portainer/pull/5353)
> > 
> > 
> > Interesting, thanks for your work
> 
> It looks like this is related to their theme/helm work. I'll pass, it looks like a lot more work to implement :)
> 
> https://docs.portainer.io/v/ce-2.9/advanced/app-templates/format

I hopefully excited for a second

**Comment by GilbN** [comment]
try using https://develop.theme-park.dev

**Comment by Dulanic** [comment]
It's good now, thanks for merging the PR :)

![image](https://user-images.githubusercontent.com/2948206/135512998-293ae861-9e4d-4e6c-a5b7-928d8ba9de7b.png)

**Comment by GilbN** [comment]
> It's good now, thanks for merging the PR :)
> 
> ![image](https://user-images.githubusercontent.com/2948206/135512998-293ae861-9e4d-4e6c-a5b7-928d8ba9de7b.png)

this too? https://imgur.com/HnVO5Yx

**Comment by deaglenomics** [comment]
I have been using this until its fixed , while not perfect its usable.
https://github.com/Vakrehus/portainer-materialio-dark-theme/blob/master/material.css

**Comment by GilbN** [comment]
> I have been using this until its fixed , while not perfect its usable.
> 
> https://github.com/Vakrehus/portainer-materialio-dark-theme/blob/master/material.css

Is it still broken on https://develop.theme-park.dev ?

**Comment by tordenflesk** [comment]
> 
> 
> > I have been using this until its fixed , while not perfect its usable.
> > https://github.com/Vakrehus/portainer-materialio-dark-theme/blob/master/material.css
> 
> Is it still broken on https://develop.theme-park.dev ?

I'm using https://gilbn.github.io/theme.park/CSS/themes/portainer/space-gray.css in Stylus. How do I test this?

**Comment by GilbN** [comment]
> > 
> 
> > 
> 
> > > I have been using this until its fixed , while not perfect its usable.
> 
> > > https://github.com/Vakrehus/portainer-materialio-dark-theme/blob/master/material.css
> 
> > 
> 
> > Is it still broken on https://develop.theme-park.dev ?
> 
> 
> 
> I'm using https://gilbn.github.io/theme.park/CSS/themes/portainer/space-gray.css in Stylus. How do I test this?


Use

https://develop.theme-park.dev/CSS/themes/portainer/portainer-base.css

https://theme-park.dev/CSS/variables/space-gray.css.css

**Comment by tordenflesk** [comment]
OK, search-box is fixed, but the input-boxes for login are still white:

https://i.imgur.com/LYpE25l.png

**Comment by deaglenomics** [comment]
Still seeing issues with text not displaying right.
![image](https://user-images.githubusercontent.com/44186043/135707872-266d7289-bf69-4a73-9e5a-93364f707270.png)

**Comment by GilbN** [comment]
> OK, search-box is fixed, but the input-boxes for login are still white:
> 
> https://i.imgur.com/LYpE25l.png



> Still seeing issues with text not displaying right. ![image](https://user-images.githubusercontent.com/44186043/135707872-266d7289-bf69-4a73-9e5a-93364f707270.png)

Try and clear cache now.

**Comment by deaglenomics** [comment]
Looks good now :)

![image](https://user-images.githubusercontent.com/44186043/135710307-00540917-40c6-48ce-bb91-c5382b79c4cc.png)

**Comment by GilbN** [comment]
This should be good now. Let me know of any other issues
