### ISSUE TITLE
Plex theme broken after Plex update

### ISSUE THREAD

**Issue by jjjonesjr33** [GilbN/theme.park#291]
**Describe the bug**

The latest Plex update broke the CSS injection and the coding via Nginx Proxy Manager. The theme does not show after the latest plex update. Plex Version 4.66.1 seems to break the CSS injection.

**Theme Install Method** (Don't skip)
- Docker run / Compose Config - Managed via Unraid Server ( unable to pull )
- Webserver subfilter Config - Nginx Proxy Manager

```
proxy_set_header Accept-Encoding "";
sub_filter
'</head>'
'<link rel="stylesheet" type="text/css" href="https://theme-park.dev/CSS/themes/plex/plex-base.css">
<link rel="stylesheet" type="text/css" href="https://theme-park.dev/CSS/variables/dark.css">
</head>';
sub_filter_once on;
```

**Application Info** (Don't skip)
- Version - Nginx-Proxy-Manager-Official
- Branch - Latest
- Container - jc21/nginx-proxy-manager

**To Reproduce**

Update Plex to the latest version

**Expected behavior**
For the theme to show, previous versions of Plex worked with the theme, nothing has changed besides Plex updating to the latest version.

**Desktop (If applicable) (please complete the following information):**
 - OS: [e.g. iOS] Windows 10, Windows 11
 - Browser [e.g. chrome, safari] Chrome, FireFox, Edge

**Smartphone (If applicable) (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 11 Pro Max
 - OS: [e.g. iOS8.1] 15.2 Devloper Build
 - Browser [e.g. stock browser, safari] Chrome, Safari

**Comment by GilbN** [comment]
Fixed on dev. Test https://develop.theme-park.dev/

**Comment by jjjonesjr33** [comment]
So I am seeing the css for the text apply, but I am still not seeing the background apply. Any thoughts?

I did switch over to what you updated to

```
proxy_set_header Accept-Encoding "";
sub_filter
'</head>'
'<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/plex/dark.css">
</head>';
sub_filter_once on;
```

Here is a snip of what mine shows
![image](https://user-images.githubusercontent.com/29973406/141656913-78f1084f-978d-45a8-91aa-6482463e107c.png)

Vs the original for the dark them.

![image](https://user-images.githubusercontent.com/29973406/141656956-395eae9a-9b6b-4e91-a551-06f4e6caabde.png)

**Comment by jjjonesjr33** [comment]
FYI: Tested with the other themes as well and they do the same thing. Color for the font, progress bar, watched/unwatched do change to the correct theme. Just no background change.

**Comment by SkalCore** [comment]
same here

**Comment by GilbN** [comment]
> So I am seeing the css for the text apply, but I am still not seeing the background apply. Any thoughts?
> 
> I did switch over to what you updated to
> 
> ```
> proxy_set_header Accept-Encoding "";
> sub_filter
> '</head>'
> '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/plex/dark.css">
> </head>';
> sub_filter_once on;
> ```
> 
> Here is a snip of what mine shows
> 
> With CSS ![image](https://user-images.githubusercontent.com/29973406/141656913-78f1084f-978d-45a8-91aa-6482463e107c.png)
> 
> Without CSS ![image](https://user-images.githubusercontent.com/29973406/141657089-3d3301db-085c-4cfb-a5fa-e05dc5f20907.png)
> 
> Vs the original for the dark them.
> 
> ![image](https://user-images.githubusercontent.com/29973406/141656956-395eae9a-9b6b-4e91-a551-06f4e6caabde.png)

Use the develop domain. https://develop.theme-park.dev/

```nginx
proxy_set_header Accept-Encoding "";
sub_filter
'</head>'
'<link rel="stylesheet" type="text/css" href="https://develop.theme-park.dev/css/base/plex/dark.css">
</head>';
sub_filter_once on;
```

**Comment by jjjonesjr33** [comment]
@GilbN that fixed it.

![image](https://user-images.githubusercontent.com/29973406/141660355-8b361a76-f577-4e0f-b273-c16f7ba70c65.png)
